### ISSUE TITLE
Figures from paper are NOT reproduced

### ISSUE THREAD

**Issue by bulli92** [pygeo/rt1#35] opened 2017-03-28 06:02 UTC
The figures for example 01 and example 02 are not the same as those within the Quast & Wagner paper. Seems that there is still something wrong here.

@raphaelquast can you please check if you can reproduce this error?

Examples can be found in the `documentation` branch.

**Comment by raphaelquast** [comment] 2017-03-28 07:54
@bulli92 There are some issues that can be solved and some that will remain...

- changed plot to display intensity instead of sigma_0  (by setting sigma0 = False)
- changed normalization of BRDF to fit the definition in the paper (by setting NormBRDF = np.pi)

unfortunately as I already mentioned there was an error in the definition of the
program I used to generate the plots for the paper... (I will try to get this corrected)

The error originated from the fact that the arguments of the functions (as also implemented
in our code) are in terms of zenith-angles... the arguments in the theory-part of the paper are in
terms of a spherical coordinate-system!
-> this resulted in an error in the definition of the fn-coefficients and consequently in an 
error in the calculation of the interaction-term.  (unfortunately the arguments of the functions
have been similarly defined for numerical testing which then resulted in an agreement of the results)

In example 1 this has no effect on the backscattered radiation due to the symmetry-properties 
of the Rayleigh-phase-function. In example 2, the interaction-term is now much more significant. 
This is reasonable since the BRDF is defined to scatter primarily in specular direction
(away from the detector) and the phase-function scatters primarily in forward-direction
(also away from the detector). So for t_0 > 40 deg most radiation that is 
scattered in direction of the detector originates from multiple-scattering contributions.

Also the fact that the interaction-term in example_2 at t_0 = 0   is much larger than in example_1 is reasonable since the phase-function now scatters primarily in forward-direction (and the BRDF is the same).

**Comment by bulli92** [comment] 2017-03-28 07:58
o.k., then it's perhaps in particular a matter how to DOCUMENT these 
differences.

A user will compare the example figures with those of the paper, like I 
did, and wonder why things look different. Thus we need to highlight 
that somehow.

**Comment by raphaelquast** [comment] 2017-03-28 09:56
yes I agree...

I planned on contacting OSA once our module has reached a certain degree of 
completion so that i can directly refer to it.

One way of documenting it in the meanwhile would be to just show how to reproduce
the error of the paper.... This can be done easily by changing the generalized scattering
angle parameter before evaluating the interaction-term and switching it back once the 
coefficients have been stored, i.e.:
```
V.a = [1.,1.,1.]
R = RT1(I0, 0., 0., 0., 0., RV=V, SRF=SRF, geometry='mono')  
fn = R.fn  # store coefficients for faster iteration 
V.a = [-1.,1.,1.]
```
This change is equivalent to setting  `p(t_0, t_ex, p_0, p_ex )        --->         p(np.pi - t_0, t_ex, p_0, p_ex ) ` during the evaluation of the fn-coefficients which is exactly the error that occured within the paper-plots

... to see the equality of the transformations:
```
for a[0] = a,   a[1] = a[2] =1. we have:

cos(THETA) =   a * cos(t_0) cos(t_ex)         + sin(t_0) sin(t_ex) cos(p_0 - p_ex)
           = - a * cos(np.pi - t_0) cos(t_ex) + sin(t_0) sin(t_ex) cos(p_0 - p_ex)
```

**Comment by bulli92** [comment] 2017-04-04 07:01
o.k., where is the right place to but these additional details?

**Comment by raphaelquast** [comment] 2017-04-04 08:25
I think it's most reasonable to add it to the end of the IPython notebook files 
(as a code that one can un-comment to see the changes) and maybe a short note in the examples-section
that refers to the IPython files.

I'll try to add it today!
(I will not add a lot of explanation since it would mainly be an explanation of how to do it wrong...)

**Comment by raphaelquast** [comment] 2017-04-04 12:31
I added an explanation to the ipython notebook of example 2.

From my side I think that's enough for the time being ... 
If you're OK with it we can close this issue

**Closed** 2017-04-04 15:01 UTC
